name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write  # create GH release
  id-token: write  # publish to PyPI (Trusted Publishing)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip build hatch

      - name: Build wheel & sdist
        run: |
          python -m build --sdist --wheel --outdir dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
        env:
          # Either trusted-publishing or classic API token
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: dist/*